//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenisProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contect
    {
        public int Id { get; set; }
        public string iletisimAdi { get; set; }
        public string iletisimAdres { get; set; }
        public string iletisimTel { get; set; }
    }
}
