//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenisProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int Id { get; set; }
        public int kiralamaId { get; set; }
        public string fiyat { get; set; }
        public string kiralamaBaslangic { get; set; }
        public string kiralamaBitis { get; set; }
        public Nullable<System.DateTime> faturaOdemeTarihi { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    
        public virtual User_Kiralama User_Kiralama { get; set; }
    }
}
