//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenisProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kortDetay
    {
        public int Id { get; set; }
        public int kortId { get; set; }
        public int saatId { get; set; }
        public System.DateTime eklenisTarihi { get; set; }
    }
}
