//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenisProjesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TenisProjesiEntities : DbContext
    {
        public TenisProjesiEntities()
            : base("name=TenisProjesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Contect> Contects { get; set; }
        public virtual DbSet<Fatura> Faturas { get; set; }
        public virtual DbSet<KiralamaDetay> KiralamaDetays { get; set; }
        public virtual DbSet<Kort> Korts { get; set; }
        public virtual DbSet<kortDetay> kortDetays { get; set; }
        public virtual DbSet<Saat> Saats { get; set; }
        public virtual DbSet<Takim> Takims { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<User_Kiralama> User_Kiralama { get; set; }
        public virtual DbSet<Abonelikler> Aboneliklers { get; set; }
        public virtual DbSet<Satislar> Satislars { get; set; }
    }
}
