//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenisProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takim
    {
        public int Id { get; set; }
        public string Adi_Soyadi { get; set; }
        public byte[] resim { get; set; }
    }
}
